version: "3"
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-127.0.0.1:5432}:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-directus}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-directus}"
      POSTGRES_DB: "${POSTGRES_DB:-directus}"


  directus:
    image: directus/directus:10.13.1
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
    depends_on:
      - database
    env_file:
      - .env
    environment:
      SECRET: "${SECRET:-directus}"

      DB_CLIENT: "pg"
      DB_HOST: "${DB_HOST:-database}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_DATABASE: "${DB_DATABASE:-directus}"
      DB_USER: "${DB_USER:-directus}"
      DB_PASSWORD: "${DB_PASSWORD:-directus}"

      CACHE_ENABLED: "false"

      ADMIN_EMAIL: "${ADMIN_EMAIL:-admin@example.com}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-d1r3ctu5}"
    logging:
      options:
        max-size: ${DOCKER_LOG_MAX_SIZE:-10m}
        max-file: ${DOCKER_LOG_MAX_FILE:-3}

    